# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run Fppt-Ig
      run: docker run -v `pwd`:/root/fpptIg/studentManager -v `pwd`/output:/root/fpptigOutput --env FPPT_IG_REPO_PATH=/root/fpptIg/studentManager --env FPPT_IG_TASK_PREFIX="SM" mario94/fppt-ig:1.0

    - name: Upload Json result
      uses: actions/upload-artifact@v1
      with:
        name: Json Result
        path: output
